apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: your-dockerhub/url-shortener
          ports:
            - containerPort: 8000
          resources:
          requests:
            cpu: "250m"      # Request 250 millicores (0.25 CPU)
            memory: "256Mi"  # Request 256MB of memory
          limits:
            cpu: "500m"      # Limit to 500 millicores (0.5 CPU)
            memory: "512Mi"